export const ADD_POLL = 'ADD_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const SET_CURRENT = 'SET_CURRENT';
export const UPDATE_POLL = 'UPDATE_POLL';
export const FILTER_POLLS = 'FILTER_POLLS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const VOTE_ERROR = '	VOTE_ERROR';
